/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:508384:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:508384:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:340173:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  if(upPressed == false) {
  upPressed = true;
  leftPressed = false;
  rightPressed = false;
  downPressed = false;
  }else{
  upPressed = false;
  }
  
} //_CODE_:button1:340173:

public void button2_click2(GButton source, GEvent event) { //_CODE_:button2:471471:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  if(leftPressed == false) {
  upPressed = false;
  leftPressed = true;
  rightPressed = false;
  downPressed = false;
  }else{
  leftPressed = false;
  }
  
} //_CODE_:button2:471471:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:921265:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());

if(rightPressed == false) {
  upPressed = false;
  leftPressed = false;
  rightPressed = true;
  downPressed = false;
  }else{
  rightPressed = false;
  }


} //_CODE_:button3:921265:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:796932:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());

if(downPressed == false) {
  upPressed = false;
  leftPressed = false;
  rightPressed = false;
  downPressed = true;
  }else{
  downPressed = false;
  }

} //_CODE_:button4:796932:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:722565:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  
  textfield1.setText("");
  
} //_CODE_:button5:722565:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  textfield1 = new GTextField(this, 15, 555, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setPromptText("Indtast navn på storby");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button1 = new GButton(this, 250, 15, 80, 60);
  button1.setText("Op");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 15, 250, 60, 80);
  button2.setText("Venstre");
  button2.setTextBold();
  button2.addEventHandler(this, "button2_click2");
  button3 = new GButton(this, 525, 250, 60, 80);
  button3.setText("Højre");
  button3.setTextBold();
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 250, 525, 80, 60);
  button4.setText("Ned");
  button4.setTextBold();
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 183, 555, 32, 30);
  button5.setText("DEL");
  button5.setLocalColorScheme(GCScheme.RED_SCHEME);
  button5.addEventHandler(this, "button5_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
