/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:508384:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:508384:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:340173:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  upPressed = true;
} //_CODE_:button1:340173:

public void button2_click2(GButton source, GEvent event) { //_CODE_:button2:471471:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  leftPressed = true;
} //_CODE_:button2:471471:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  textfield1 = new GTextField(this, 250, 550, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setPromptText("Enter city name");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button1 = new GButton(this, 250, 25, 80, 50);
  button1.setText("Up");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 25, 250, 50, 80);
  button2.setText("Left");
  button2.setTextBold();
  button2.addEventHandler(this, "button2_click2");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GButton button1; 
GButton button2; 
